### ISSUE TITLE
windows submit job failure

### ISSUE THREAD

**Issue by muxinyun** [harbby/sylph#85] opened 2019-04-17 08:16 UTC
sumbit job from windows OS，some jars upload hdfs, but program cannot find some class，because，classpath's separator on windows is  semicolon, on linux is  colon。

**Comment by harbby** [comment] 2019-04-17 08:46
Thank you for your feedback. We will fix it as soon as possible

**Comment by harbby** [comment] 2019-04-24 03:37
This issue is caused by https://github.com/harbby/gadtry/pull/12 and will be fixed at 0.5.1 and 0.6

**Closed** 2019-05-14 14:52 UTC
Labels: bug
